---
title: "carbon data exploration"
author: "Rachel Bash"
date: "4/2/2019"
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Exploration of Raw Carbon Data


```{r}
getwd()

#load all required packages
library(tidyverse)
library(dplyr)
library(lubridate)

```



```{r}


#View data
#View(carbon.data)
```

```{r}
#exploratory
colnames(carbon.data)
str(carbon.data)
summary(carbon.data)
dim(carbon.data)
```

```{r}
#set date
carbon.data$sampledate <- as.Date(carbon.data$sampledate, format = "%m/%d/%y")
head(carbon.data$sampledate)
```

```{r}
#data visualization
ggplot(carbon.data) +
  geom_histogram(aes(x=absorbance), color="#1f78b4", fill="#1f78b4") +
  labs(x= "Frequency", y="Absorbance value")


ggplot(carbon.data) +
  geom_histogram(aes(x=doc))

ggplot(carbon.data) +
  geom_freqpoly(aes(x=absorbance, color = depth)) +
  labs(x= "Absorbance", y = "Frequency", color= "Depth") +
  scale_color_brewer(palette = "Paired") #shows absorbance differences depending on depth in lake

ggplot(carbon.data) +
  geom_point(aes(x = absorbance, y = doc, color=year4)) +
  scale_color_viridis(option="viridis", direction= -1) +
  labs(x="Absorbance", y="Dissolved Organic Carbon, mg/L", color="Year") #absorbance and doc positively linearly related

ggplot(carbon.data) +
  geom_point(aes(x = depth_id, y = absorbance))


ggplot(carbon.data) +
  geom_point(aes(x = sampledate, y = absorbance, color = lakename)) + 
  scale_x_date(limits = as.Date(c('1996-06-03','2016-08-17'))) #shows absorbance over time

ggplot(carbon.data) +
  geom_point(aes(x = absorbance, y = DIC_uM)) #perhaps a small positive correlation between absorbance and DIC

ggplot(carbon.data.processed) +
  geom_point(aes(x=depth, y = absorbance, color = lakename)) #shows absorbance by depth and lakename

library(kableExtra)


```

```{r}
#filtering
carbon.data.processed <- carbon.data %>%
  filter(depth %in% c("PML", "Hypolimnion", "Epilimnion", "Metalimnion")) %>%
  filter(lakename %in% c("Peter Lake", "Paul Lake", "East Long Lake", "Tuesday Lake", "West Long Lake")) %>%
  select(lakename:depth_id, DIC_mg, DIC_uM, doc, absorbance)


summary(carbon.data.processed)
#decided to use depth categories instead of depth values because absorbance and doc are only measured using Epi, Meta, and Hypo categorizations

```

```{r}
#write csv
write.csv(carbon.data.processed, row.names = FALSE, file = "./processed-data/NTL-LTER_Carbon_Data_Processed.csv")
```
 
